// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR4tgDU-j-ssGb66eJiDioND3-cj74aYM',
    appId: '1:314684599012:web:aa69f737bbe6b04539daf1',
    messagingSenderId: '314684599012',
    projectId: 'marinelink-c431d',
    authDomain: 'marinelink-c431d.firebaseapp.com',
    storageBucket: 'marinelink-c431d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCklvFkgv6GiXzE8k2n3s96vewOF2uIBYM',
    appId: '1:314684599012:android:ad12bf74cc1cb7d639daf1',
    messagingSenderId: '314684599012',
    projectId: 'marinelink-c431d',
    storageBucket: 'marinelink-c431d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf4Pppn-A5_GMu3cIbpKkRqNUSWOpWCgM',
    appId: '1:314684599012:ios:05aabbdec5936ddd39daf1',
    messagingSenderId: '314684599012',
    projectId: 'marinelink-c431d',
    storageBucket: 'marinelink-c431d.firebasestorage.app',
    iosBundleId: 'com.example.fishExportManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf4Pppn-A5_GMu3cIbpKkRqNUSWOpWCgM',
    appId: '1:314684599012:ios:05aabbdec5936ddd39daf1',
    messagingSenderId: '314684599012',
    projectId: 'marinelink-c431d',
    storageBucket: 'marinelink-c431d.firebasestorage.app',
    iosBundleId: 'com.example.fishExportManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR4tgDU-j-ssGb66eJiDioND3-cj74aYM',
    appId: '1:314684599012:web:2c684024f13b98e939daf1',
    messagingSenderId: '314684599012',
    projectId: 'marinelink-c431d',
    authDomain: 'marinelink-c431d.firebaseapp.com',
    storageBucket: 'marinelink-c431d.firebasestorage.app',
  );
}
